# Generated by Django 4.0.3 on 2022-04-06 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(blank=True, max_length=20, verbose_name='для ПО')),
            ],
            options={
                'verbose_name': 'для ПО',
                'verbose_name_plural': 'для ПО',
            },
        ),
        migrations.CreateModel(
            name='Ispolnitel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=25, verbose_name='фамилия')),
                ('name', models.CharField(max_length=16, verbose_name='имя')),
                ('patronymic', models.CharField(max_length=16, verbose_name='отчество')),
                ('dolzhnost', models.CharField(max_length=150, verbose_name='должность')),
                ('mail1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='электронная почта')),
            ],
            options={
                'verbose_name': 'ответственный',
                'verbose_name_plural': 'ответственные',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kratknaim', models.CharField(max_length=255, verbose_name='краткое наименование')),
                ('polnnaim', models.TextField(max_length=500, verbose_name='полное наименование')),
                ('objectaip', models.TextField(blank=True, max_length=500, verbose_name='объект по АИП')),
                ('numberobjectaip', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='№ АИП')),
                ('redzone', models.BooleanField(default=False, verbose_name='объект красной зоны')),
            ],
            options={
                'verbose_name': 'объект',
                'verbose_name_plural': 'объекты',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kratknaim', models.CharField(max_length=50, verbose_name='краткое наименование организации')),
                ('polnnaim', models.CharField(max_length=255, verbose_name='полное наименование организации')),
                ('mail1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='общая электронная почта')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
            },
        ),
        migrations.CreateModel(
            name='Shtab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateshtabe', models.DateField(blank=True, null=True)),
                ('predsedatel', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'verbose_name': 'штаб',
                'verbose_name_plural': 'штабы',
            },
        ),
        migrations.CreateModel(
            name='Sortforpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'сортировка для ПО',
                'verbose_name_plural': 'сортировка для ПО',
            },
        ),
        migrations.CreateModel(
            name='Statysisp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(blank=True, max_length=20, verbose_name='статус исполнения')),
            ],
            options={
                'verbose_name': 'статус исполнения',
                'verbose_name_plural': 'статусы исполнения',
            },
        ),
        migrations.CreateModel(
            name='Poruchenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberpor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='№')),
                ('por', models.TextField(verbose_name='поручение')),
                ('srokisp', models.DateField(blank=True, null=True, verbose_name='срок исполнения')),
                ('dateisp', models.DateField(blank=True, null=True, verbose_name='дата исполнения')),
                ('itogi', models.TextField(blank=True, verbose_name='итоги')),
                ('otprzapr', models.TextField(blank=True, verbose_name='информация по направлению запросов')),
                ('polzapr', models.TextField(blank=True, verbose_name='bнформация по получению ответа на запрос')),
                ('kratkopisisppor', models.TextField(blank=True, verbose_name='краткое описание исполнения поручения')),
                ('anal', models.TextField(blank=True, verbose_name='аналитика ("архивные" комментарии)')),
                ('obiaz', models.BooleanField(default=False, verbose_name='принятые обязательства')),
                ('gpr', models.BooleanField(default=False, verbose_name='ГПР')),
                ('factsrivsroka', models.BooleanField(default=False, verbose_name='Факты срыва срока')),
                ('porneizprot', models.BooleanField(default=False, verbose_name='Поручения не из протокола')),
                ('kritvopr', models.BooleanField(default=False, verbose_name='Критичный вопрос')),
                ('forpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shtab.forpo', verbose_name='для ПО')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shtab.object', verbose_name='объект')),
                ('otv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_as_otv', to='shtab.ispolnitel', verbose_name='ответственный')),
                ('otvotpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ответственный от ПО')),
                ('shtab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shtab.shtab', verbose_name='штаб')),
                ('soisp', models.ManyToManyField(blank=True, null=True, related_name='tasks_as_soisp', to='shtab.ispolnitel', verbose_name='соисполнитель')),
                ('statysisp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shtab.statysisp', verbose_name='статус исполнения')),
            ],
            options={
                'verbose_name': 'поручение',
                'verbose_name_plural': 'поручения',
            },
        ),
        migrations.AddField(
            model_name='object',
            name='sortforpo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shtab.sortforpo', verbose_name='сортировка для ПО'),
        ),
        migrations.AddField(
            model_name='ispolnitel',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shtab.organization'),
        ),
    ]
