# Generated by Django 4.0.3 on 2022-04-06 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shtab', '0002_alter_statysisp_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predsedatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predsedatel', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'verbose_name': 'председатель штаба',
                'verbose_name_plural': 'председатели штабов',
            },
        ),
        migrations.AlterField(
            model_name='shtab',
            name='predsedatel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shtab.predsedatel'),
        ),
    ]
