# Generated by Django 4.0.3 on 2022-04-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shtab', '0003_predsedatel_alter_shtab_predsedatel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predsedatel',
            name='predsedatel',
            field=models.CharField(blank=True, max_length=15, verbose_name='председатель'),
        ),
        migrations.AlterField(
            model_name='shtab',
            name='dateshtabe',
            field=models.DateField(blank=True, null=True, verbose_name='дата проведения штаба'),
        ),
        migrations.AlterField(
            model_name='shtab',
            name='predsedatel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shtab.predsedatel', verbose_name='председатель штаба'),
        ),
    ]
