# Generated by Django 4.0.3 on 2022-04-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shtab', '0004_alter_predsedatel_predsedatel_alter_shtab_dateshtabe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poruchenie',
            options={'ordering': ['shtab'], 'verbose_name': 'поручение', 'verbose_name_plural': 'поручения'},
        ),
    ]
