# Generated by Django 4.0.3 on 2022-04-09 15:13

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shtab', '0005_alter_poruchenie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poruchenie',
            name='otvotpo',
            field=models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ответственный от ПО'),
        ),
    ]
